In [87]:
import pandas as pd
import numpy as np
from datetime import timedelta

In [88]:
data = pd.read_csv("data.csv")
data

,Time,COURANT ValueY,DEBIT EAU ValueY,SOLIDE ValueY,PUISSANCE ValueY,refus_tamis
0,2022-01-28 00:00:00,67.253113,10.185185,121.003326,576.604736,20.849820
1,2022-01-28 00:01:00,67.253113,10.185185,121.003326,576.604736,20.849820
2,2022-01-28 00:02:00,67.253113,10.185185,121.003326,576.604736,20.849820
3,2022-01-28 00:03:00,67.253113,10.185185,121.003326,576.604736,20.849820
4,2022-01-28 00:04:00,67.253113,10.185185,121.003326,576.604736,20.849820
...,...,...,...,...,...,...
101066,2022-10-20 16:57:00,NaN,NaN,NaN,507.211636,19.755739
101067,2022-10-20 16:58:00,NaN,NaN,NaN,511.160186,19.755739
101068,2022-10-20 16:59:00,NaN,NaN,NaN,509.005283,19.755739
101069,2022-10-20 17:00:00,NaN,NaN,NaN,510.360491,19.755739
101070,2022-10-20 17:01:00,NaN,NaN,NaN,509.105051,19.755739

In [89]:
data['Time'] = pd.to_datetime(data['Time'], format="%Y/%m/%d %H:%M:%S")
data.dtypes

Time                datetime64[ns]
COURANT ValueY             float64
DEBIT EAU ValueY           float64
SOLIDE ValueY              float64
PUISSANCE ValueY           float64
refus_tamis                float64
dtype: object

In [90]:
(data.isna().sum()/data.shape[0]).sort_values(ascending=True)

Time                0.000000
PUISSANCE ValueY    0.000000
refus_tamis         0.000000
COURANT ValueY      0.001346
DEBIT EAU ValueY    0.002820
SOLIDE ValueY       0.011606
dtype: float64

In [91]:
print(f"Min : {data['Time'].min()}")    
print(f"MAx : {data['Time'].max()}")

Min : 2022-01-28 00:00:00
MAx : 2022-10-20 17:01:00

In [92]:
t = pd.to_datetime("2022-01-28 00:00:00")
i = 1
x = f"Poste {i+1}"
x

'Poste 2'

In [93]:
def value_by_poste(data):
    list_courant,list_debit_eau,list_solide,list_puissance,list_time,list_poste = [],[],[],[],[],[]
    time_start = pd.to_datetime("2022-01-28 00:00:00")
    columns = data.columns
    while(time_start <= pd.to_datetime("2022-10-20 17:01:00")):
        for i in range(3):
            interv = data[data[columns[0]].between(time_start,time_start + timedelta(hours=8))]
            if interv.shape[0] != 0:
                list_courant.append(interv["COURANT ValueY"].mean())
                list_debit_eau.append(interv["DEBIT EAU ValueY"].mean())
                list_solide.append(interv["SOLIDE ValueY"].mean())
                list_puissance.append(interv["PUISSANCE ValueY"].mean())
                list_time.append(time_start)
                #list_poste.append(f"Poste {i+1}")
            time_start = time_start + timedelta(hours=8)
    new_data = pd.DataFrame(data=zip(list_time,list_courant,list_debit_eau,list_solide,list_puissance),columns=["Time","COURANT ValueY","DEBIT EAU ValueY","SOLIDE ValueY","PUISSANCE ValueY"])
    return new_data

In [94]:
new_data = value_by_poste(data)
new_data

,Time,COURANT ValueY,DEBIT EAU ValueY,SOLIDE ValueY,PUISSANCE ValueY
0,2022-01-28 00:00:00,64.767911,10.011742,120.091735,555.430570
1,2022-01-28 08:00:00,64.193674,10.009246,120.023860,550.337705
2,2022-01-28 16:00:00,63.912885,9.708684,114.701485,547.888626
3,2022-01-29 00:00:00,63.892667,9.382377,108.993462,548.397254
4,2022-01-29 08:00:00,63.030948,9.503467,109.672496,540.445674
...,...,...,...,...,...
212,2022-10-19 08:00:00,59.034442,9.738259,103.756132,506.144457
213,2022-10-19 16:00:00,58.196467,9.514840,108.719497,498.817430
214,2022-10-20 00:00:00,58.120637,9.477183,109.858441,498.298019
215,2022-10-20 08:00:00,56.303701,9.846997,101.390345,483.159073
216,2022-10-20 16:00:00,NaN,NaN,NaN,514.251519

In [95]:
(new_data.isna().sum()/new_data.shape[0]).sort_values(ascending=True)

Time                0.000000
PUISSANCE ValueY    0.000000
COURANT ValueY      0.004608
DEBIT EAU ValueY    0.009217
SOLIDE ValueY       0.018433
dtype: float64

Refus_Tamis

In [96]:
new_data=new_data.assign(refus_tamis=0)

In [97]:
data_refus_tamis = pd.read_excel("De 11_02 à 17_02 2022\Refus Tamis\TB_D80_et_performances_Usine_Février_2022.xlsx")
data_refus_tamis_octobre = pd.read_excel("De 15_09 à 20_10 2022\Refus Tamis\TB_D80_et_performances_Usine_Octobre_2022.xlsx")
data_refus_tamis_septembre = pd.read_csv("De 15_09 à 20_10 2022\Refus Tamis\data_refus_tamis_septembre.csv")
data_refus_tamis_aout = pd.read_excel("De 23_08 à 15_09 2022\Refus Tamis\TB_D80_et_performances_Usine_Août_2022.xlsx")
data_refus_tamis_septembre_2 = pd.read_excel("De 23_08 à 15_09 2022\Refus Tamis\TB_D80_et_performances_Usine_Septembre_2022.xlsx")
data_refus_tamis_janvier = pd.read_excel("De 28_01 à 03_02 2022\Refus Tamis\TB_D80_et_performances_Usine_Janvier_2022.xlsx")
data_refus_tamis_fevrier = pd.read_excel("De 28_01 à 03_02 2022\Refus Tamis\TB_D80_et_performances_Usine_Février_2022.xlsx")

In [98]:
data_refus_tamis_septembre['Jours'] = pd.to_datetime(data_refus_tamis_septembre['Jours'], format="%Y/%m/%d %H:%M:%S")

In [99]:
def process_refu_tamis(data):
    data.dropna(how='all',inplace=True)
    del data["Unnamed: 0"]
    data.rename(columns={'Unnamed: 1':"Jours", 'Unnamed: 2':"Poste",'Unnamed: 3':"Refus Tamis +500 en % QA"}, inplace=True)
    data.drop(index=1,inplace=True)
    for i,line in enumerate(data.index):
        if data.iloc[i]["Jours"] is np.nan:
            data.iloc[i]["Jours"] = data.iloc[i-1]["Jours"]
        if (data.iloc[i]["Refus Tamis +500 en % QA"] is np.nan):
            data.iloc[i]["Refus Tamis +500 en % QA"] = data.iloc[i-1]["Refus Tamis +500 en % QA"]
    data.drop(data.tail(3).index,inplace = True)
    data['Jours'] = pd.to_datetime(data['Jours'], format="%Y/%m/%d %H:%M:%S")
    data["Refus Tamis +500 en % QA"] = data["Refus Tamis +500 en % QA"].astype(float)

In [100]:
process_refu_tamis(data_refus_tamis)
process_refu_tamis(data_refus_tamis_octobre)
process_refu_tamis(data_refus_tamis_aout)
process_refu_tamis(data_refus_tamis_septembre_2)
process_refu_tamis(data_refus_tamis_janvier)
process_refu_tamis(data_refus_tamis_fevrier)

In [101]:
def add_refus_tamis(refus_tamis,data):
    for i,line in enumerate(refus_tamis.index):
        v1 = refus_tamis.iloc[i]["Jours"]
        if i==0:
            v3 = v1
            for j in range(3):
                data.loc[data.Time == v3,'refus_tamis']= list(refus_tamis[refus_tamis["Jours"] == v1]["Refus Tamis +500 en % QA"])[j]
                v3 = v3 + timedelta(hours=8)
            v2 = v1
        else:
            if v1 != v2:
                v3 = v1
                for j in range(3):
                    data.loc[data.Time == v3,'refus_tamis']= list(refus_tamis[refus_tamis["Jours"] == v1]["Refus Tamis +500 en % QA"])[j]
                    v3 = v3 + timedelta(hours=8)
                v2 = v1

In [102]:
add_refus_tamis(data_refus_tamis,new_data)
add_refus_tamis(data_refus_tamis_octobre,new_data)
add_refus_tamis(data_refus_tamis_septembre,new_data)
add_refus_tamis(data_refus_tamis_aout,new_data)
add_refus_tamis(data_refus_tamis_septembre_2,new_data)
add_refus_tamis(data_refus_tamis_janvier,new_data)
add_refus_tamis(data_refus_tamis_fevrier,new_data)

In [103]:
new_data

,Time,COURANT ValueY,DEBIT EAU ValueY,SOLIDE ValueY,PUISSANCE ValueY,refus_tamis
0,2022-01-28 00:00:00,64.767911,10.011742,120.091735,555.430570,15.255906
1,2022-01-28 08:00:00,64.193674,10.009246,120.023860,550.337705,22.246696
2,2022-01-28 16:00:00,63.912885,9.708684,114.701485,547.888626,25.059102
3,2022-01-29 00:00:00,63.892667,9.382377,108.993462,548.397254,23.607689
4,2022-01-29 08:00:00,63.030948,9.503467,109.672496,540.445674,20.491361
...,...,...,...,...,...,...
212,2022-10-19 08:00:00,59.034442,9.738259,103.756132,506.144457,19.743052
213,2022-10-19 16:00:00,58.196467,9.514840,108.719497,498.817430,19.743052
214,2022-10-20 00:00:00,58.120637,9.477183,109.858441,498.298019,19.743052
215,2022-10-20 08:00:00,56.303701,9.846997,101.390345,483.159073,19.743052
216,2022-10-20 16:00:00,NaN,NaN,NaN,514.251519,19.743052

In [104]:
new_data.to_csv("data_3_values_by_day.csv",index=False)