In [73]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn import metrics
import xgboost as xgb

In [3]:
data = pd.read_csv("data.csv")
data

,Time,COURANT ValueY,DEBIT EAU ValueY,SOLIDE ValueY,PUISSANCE ValueY,refus_tamis
0,2022-01-28 00:00:00,67.253113,10.185185,121.003326,576.604736,20.849820
1,2022-01-28 00:01:00,67.253113,10.185185,121.003326,576.604736,20.849820
2,2022-01-28 00:02:00,67.253113,10.185185,121.003326,576.604736,20.849820
3,2022-01-28 00:03:00,67.253113,10.185185,121.003326,576.604736,20.849820
4,2022-01-28 00:04:00,67.253113,10.185185,121.003326,576.604736,20.849820
...,...,...,...,...,...,...
101066,2022-10-20 16:57:00,NaN,NaN,NaN,507.211636,19.755739
101067,2022-10-20 16:58:00,NaN,NaN,NaN,511.160186,19.755739
101068,2022-10-20 16:59:00,NaN,NaN,NaN,509.005283,19.755739
101069,2022-10-20 17:00:00,NaN,NaN,NaN,510.360491,19.755739
101070,2022-10-20 17:01:00,NaN,NaN,NaN,509.105051,19.755739

In [6]:
data['Time'] = pd.to_datetime(data['Time'], format="%Y/%m/%d %H:%M:%S")
data.dtypes

Time                datetime64[ns]
COURANT ValueY             float64
DEBIT EAU ValueY           float64
SOLIDE ValueY              float64
PUISSANCE ValueY           float64
refus_tamis                float64
dtype: object

In [21]:
X = data[["Time","COURANT ValueY","DEBIT EAU ValueY","SOLIDE ValueY","refus_tamis"]]
X

,Time,COURANT ValueY,DEBIT EAU ValueY,SOLIDE ValueY,refus_tamis
0,2022-01-28 00:00:00,67.253113,10.185185,121.003326,20.849820
1,2022-01-28 00:01:00,67.253113,10.185185,121.003326,20.849820
2,2022-01-28 00:02:00,67.253113,10.185185,121.003326,20.849820
3,2022-01-28 00:03:00,67.253113,10.185185,121.003326,20.849820
4,2022-01-28 00:04:00,67.253113,10.185185,121.003326,20.849820
...,...,...,...,...,...
101066,2022-10-20 16:57:00,NaN,NaN,NaN,19.755739
101067,2022-10-20 16:58:00,NaN,NaN,NaN,19.755739
101068,2022-10-20 16:59:00,NaN,NaN,NaN,19.755739
101069,2022-10-20 17:00:00,NaN,NaN,NaN,19.755739
101070,2022-10-20 17:01:00,NaN,NaN,NaN,19.755739

In [22]:
y = data[["Time","PUISSANCE ValueY"]]
y

                      Time  PUISSANCE ValueY
0      2022-01-28 00:00:00        576.604736
1      2022-01-28 00:01:00        576.604736
2      2022-01-28 00:02:00        576.604736
3      2022-01-28 00:03:00        576.604736
4      2022-01-28 00:04:00        576.604736
...                    ...               ...
101066 2022-10-20 16:57:00        507.211636
101067 2022-10-20 16:58:00        511.160186
101068 2022-10-20 16:59:00        509.005283
101069 2022-10-20 17:00:00        510.360491
101070 2022-10-20 17:01:00        509.105051

[101071 rows x 2 columns]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [24]:
X_train

,Time,COURANT ValueY,DEBIT EAU ValueY,SOLIDE ValueY,refus_tamis
69604,2022-09-28 20:11:00,63.847848,10.496355,138.799050,18.198089
6525,2022-02-01 12:45:00,63.230435,8.834756,115.090903,27.598417
33437,2022-09-03 07:15:00,0.000000,0.000000,0.000000,22.282692
91262,2022-10-13 21:33:00,60.067037,7.572459,112.508139,20.857343
82097,2022-10-07 12:46:00,60.978931,12.380526,148.999579,17.205847
...,...,...,...,...,...
6265,2022-02-01 08:25:00,63.491083,9.064067,108.885815,27.598417
54886,2022-09-18 14:42:00,64.851678,10.965385,114.757178,21.232549
76820,2022-10-03 20:47:00,62.246168,9.137973,99.732350,18.734397
860,2022-01-28 14:20:00,64.892504,10.041835,120.995188,20.849820
15795,2022-02-16 02:28:00,64.216317,10.280858,118.929445,19.930912

In [25]:
y_train

                     Time  PUISSANCE ValueY
69604 2022-09-28 20:11:00        546.989604
6525  2022-02-01 12:45:00        540.130174
33437 2022-09-03 07:15:00          0.000000
91262 2022-10-13 21:33:00        512.548374
82097 2022-10-07 12:46:00        523.840664
...                   ...               ...
6265  2022-02-01 08:25:00        549.050615
54886 2022-09-18 14:42:00        556.088049
76820 2022-10-03 20:47:00        533.409559
860   2022-01-28 14:20:00        558.421674
15795 2022-02-16 02:28:00        549.960215

[70749 rows x 2 columns]

In [26]:
(X_train.isna().sum()/X_train.shape[0]).sort_values(ascending=True)

Time                0.000000
refus_tamis         0.000000
COURANT ValueY      0.001399
DEBIT EAU ValueY    0.002982
SOLIDE ValueY       0.011831
dtype: float64

In [35]:
X_train_1 = X_train[["COURANT ValueY","DEBIT EAU ValueY","SOLIDE ValueY","refus_tamis"]]
X_test_1 = X_test[["COURANT ValueY","DEBIT EAU ValueY","SOLIDE ValueY","refus_tamis"]]
y_train_1 = y_train[["PUISSANCE ValueY"]]
y_test_1 = y_test[["PUISSANCE ValueY"]]

Remplacer les NaNs par le moyen

In [36]:
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
X_train_1 = pd.DataFrame(imputer.fit_transform(X_train_1), columns=["COURANT ValueY","DEBIT EAU ValueY","SOLIDE ValueY","refus_tamis"],index=X_train_1.index)
X_train_1

       COURANT ValueY  DEBIT EAU ValueY  SOLIDE ValueY  refus_tamis
69604       63.847848         10.496355     138.799050    18.198089
6525        63.230435          8.834756     115.090903    27.598417
33437        0.000000          0.000000       0.000000    22.282692
91262       60.067037          7.572459     112.508139    20.857343
82097       60.978931         12.380526     148.999579    17.205847
...               ...               ...            ...          ...
6265        63.491083          9.064067     108.885815    27.598417
54886       64.851678         10.965385     114.757178    21.232549
76820       62.246168          9.137973      99.732350    18.734397
860         64.892504         10.041835     120.995188    20.849820
15795       64.216317         10.280858     118.929445    19.930912

[70749 rows x 4 columns]

In [37]:
(X_train_1.isna().sum()/X_train_1.shape[0]).sort_values(ascending=True)

COURANT ValueY      0.0
DEBIT EAU ValueY    0.0
SOLIDE ValueY       0.0
refus_tamis         0.0
dtype: float64

In [40]:
X_test_1 = pd.DataFrame(imputer.transform(X_test_1), columns=["COURANT ValueY","DEBIT EAU ValueY","SOLIDE ValueY","refus_tamis"],index=X_test_1.index)
X_test_1

       COURANT ValueY  DEBIT EAU ValueY  SOLIDE ValueY  refus_tamis
42948       67.023172         11.951982     113.938416    15.061272
25876       69.891476         13.834985     133.281529    20.333638
31731        0.000000          0.000000       0.000000    22.287458
83965       63.273629          9.926752     113.373715    22.736659
96783       60.242243          7.080078     109.733978    21.875764
...               ...               ...            ...          ...
25447       69.218495         13.411925     136.186132    22.824441
81205       57.821135          8.567732     112.995690    16.236483
1028        64.436947          9.780213     119.369394    20.849820
45903       64.087177         11.186833     116.803059    18.879022
28076       67.859432         11.182749     110.803675    19.992224

[30322 rows x 4 columns]

In [41]:
(X_test_1.isna().sum()/X_test_1.shape[0]).sort_values(ascending=True)

COURANT ValueY      0.0
DEBIT EAU ValueY    0.0
SOLIDE ValueY       0.0
refus_tamis         0.0
dtype: float64

Polynomial regression
KNN Regression
SVM
XGBoost

Linear Regression

In [45]:
lin_reg = LinearRegression()
lin_reg.fit(X_train_1, y_train_1)

LinearRegression()

In [56]:
lin_reg.score(X_test_1, y_test_1)

0.9771830489266711

Polynomial Regression

In [50]:
poly_reg = PolynomialFeatures(degree=4)
X_poly = poly_reg.fit_transform(X_train_1)
pol_reg = LinearRegression()
pol_reg.fit(X_poly, y_train_1)

LinearRegression()

In [53]:
X_test_poly = poly_reg.transform(X_test_1)

In [55]:
pol_reg.score(X_test_poly, y_test_1)

0.9801527916809344

KNN Regression

In [47]:
knn_model = KNeighborsRegressor(n_neighbors=5).fit(X_train_1, y_train_1)
score_knn = knn_model.score(X_test_1, y_test_1)
score_knn

0.9929201297357174

In [65]:
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train_1, y_train_1)
regressor.score(X_test_1, y_test_1)

c:\Users\Amine DD\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.9754108356901559

XGBoost

In [75]:
model = xgb.XGBRegressor()
model.fit(X_train_1, y_train_1)
print(model)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
             grow_policy='depthwise', importance_type=None,
             interaction_constraints='', learning_rate=0.300000012, max_bin=256,
             max_cat_threshold=64, max_cat_to_onehot=4, max_delta_step=0,
             max_depth=6, max_leaves=0, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=0, ...)

In [76]:
model.score(X_test_1, y_test_1)

0.9922808738732618

Evaluation par RMSE de ces 4 algorithme

In [80]:
print("Linear Regression: ", np.sqrt(metrics.mean_squared_error(y_test_1,lin_reg.predict(X_test_1))))
print("Polynomial Regression: ", np.sqrt(metrics.mean_squared_error(y_test_1,pol_reg.predict(poly_reg.transform(X_test_1)))))
print("KNN Regression: ", np.sqrt(metrics.mean_squared_error(y_test_1,knn_model.predict(X_test_1))))
print("XGBoost Regression: ", np.sqrt(metrics.mean_squared_error(y_test_1,model.predict(X_test_1))))

Linear Regression:  22.18514035880203
Polynomial Regression:  20.691076633659875
KNN Regression:  12.357938366244202
XGBoost Regression:  12.903794668156316